-- problem sql from London Borough of Hackney
DELETE FROM DOCSADM.SECURITY
 WHERE THING IN 
 (
	SELECT P.SYSTEM_ID FROM DOCSADM.PROFILE P WHERE 
	( 
		(P.SYSTEM_ID = 42171479) 
	OR P.SYSTEM_ID IN 
		(
			SELECT P.SYSTEM_ID 
			FROM DOCSADM.[FOLDER_ITEM] FI 
				INNER JOIN DOCSADM.[PROFILE] P ON P.DOCNUMBER = FI.DOCNUMBER
			WHERE FI.PARENT = 1253745 AND FI.PARENT_LIBRARY = 0 AND P.ITEM_TYPE IN( N'D',N'A')
				AND FI.NODE_TYPE IN( N'D',N'P',N'C') 
		)
	) 
	AND P.INHERITS_FROM  = 2286 AND P.INHERIT_SECURITY = N'Y'
) 
AND NOT EXISTS (SELECT * FROM DOCSADM.SECURITY S WHERE S.THING = 2286 AND S.PERSONORGROUP = DOCSADM.SECURITY.PERSONORGROUP)


-- proposed change for SQL command for London Borough of Hackney
DELETE FROM DOCSADM.SECURITY
WHERE THING IN 
(
	select 42171479
	union
	SELECT P.SYSTEM_ID 
	FROM DOCSADM.PROFILE P 
	WHERE P.SYSTEM_ID in 
	(
 		SELECT P.SYSTEM_ID 
		FROM DOCSADM.[FOLDER_ITEM] FI 
			INNER JOIN DOCSADM.[PROFILE] P ON P.DOCNUMBER = FI.DOCNUMBER
		WHERE FI.PARENT = 1253745 AND FI.PARENT_LIBRARY = 0 AND P.ITEM_TYPE IN( N'D',N'A') AND FI.NODE_TYPE IN( N'D',N'P',N'C') 
	) 
	AND P.INHERITS_FROM  = 2286 AND P.INHERIT_SECURITY = N'Y'
)
AND NOT EXISTS (SELECT * FROM DOCSADM.SECURITY S WHERE S.THING = 2286 AND S.PERSONORGROUP = DOCSADM.SECURITY.PERSONORGROUP)

