SELECT A0.SYSTEM_ID, A0.DOCNUMBER,A0.STATUS,
	A0.DEFAULT_RIGHTS,
	A1.ACCESSRIGHTS,
	A1.PERSONORGROUP,A3.FULL_NAME as Author,A0.DOCNAME,A2.APPLICATION
FROM DOCSADM.APPS A2,
	DOCSADM.CLIENT A5,
	DOCSADM.MATTER A4,
	DOCSADM.PEOPLE A3,
	DOCSADM.PROFILE A0,
	DOCSADM.SECURITY A1 
WHERE (A0.APPLICATION*=A2.SYSTEM_ID) AND 
	(A0.AUTHOR*=A3.SYSTEM_ID) AND 
	(A1.THING = A0.SYSTEM_ID) AND
	(A1.PERSONORGROUP in (
		select 11519477 
		union 
		select groups_system_id from docsadm.peoplegroups pg, docsadm.groups g 
		where people_system_id = 11519477 and pg.groups_system_id = g.system_id and g.disabled <> 'Y'
		) ) AND 
	(A0.MATTER=A4.SYSTEM_ID) AND 
	(A4.CLIENT_ID=A5.SYSTEM_ID) AND ((A5.CLIENT_ID = '70000')) 
ORDER BY A0.LAST_EDIT_DATE DESC, A0.DOCNUMBER ASC 




